version: '3.8'                                     # Versión del Docker-Compose

services:
   mongodb:
      container_name: mongodb                      # Nombre al contenedor
      image: mongo                                 # Se puede indicar la version con :6.2
      restart: always                              # Por si falla se vuelva a iniciar
      ports:
         - 27017:27017                             # Inicamos el puerto pExterior:pDefecto
      environment:
         - MONGO_INITDB_ROOT_USERNAME=admin        # Variable de entorno USER
         - MONGO_INITDB_ROOT_PASSWORD=admin        # Variable de entorno PASSWORD
      logging:
         driver: none                              # Ocultar los logs en la consola

   web:
      container_name: appNode
      restart: always
      build: .                                     # Buscara el archivo Dockerfile
      ports:
         - 4000:3000
      environment:
         - SESSION_KEY=CoopRude/ashy584@
         - MONGO_SESSION=mongodb://admin:admin@mongodb/sessionSave
         - MONGO_DB=mongodb://admin:admin@mongodb/parrilladacocon
      links:
         - "mongodb"                               # Enlazarlo a un servicio (Ej.: mongodb)
